Updates afero lab to handle both legacy and web flow authentication
aferodeveloper/AferoSwiftSDK pull request #35
Opened 2022-02-20 06:59 UTC by marnberg

Enable configuration with both authenticatorCert and hubby service.

2022-02-20 15:22 UTC, jrmiddle requested changes
One last question—do all of the unit tests pass? They _should_, as I don't see anything here that would bother them, but just checking. Otherwise, with the exception of the typo in the new bundle ID, this looks good!

2022-02-20 15:22 UTC, jrmiddle commented on AferoSwiftSDK/Core/Models/Account.swift
> +//            if firstName == nil && lastName == nil && name == nil {
We can just drop this altogether.

2022-02-20 15:22 UTC, jrmiddle commented on Examples/AferoLab/AferoLab.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = io.afero.demo.examle;
Typo, should be: `...demo.example`

2022-02-20 15:22 UTC, jrmiddle commented on Examples/AferoLab/AferoLab/Base.lproj/LaunchScreen.storyboard
> +                                <rect key="frame" x="87.5" y="210.5" width="200" height="246"/>
No big whup, but did something get nudged? Looks like something was knocked out of alignment.

2022-02-22 02:15 UTC, marnberg commented
Thank you @jrmiddle for the feedback. I updated the softhub version to 1.8.0 and fixed the unintended changes

2022-02-25 20:39 UTC, merged